name: On Update agricoladb-server lambroll

on:
  push:
    branches: [main]
    paths:
      - components/agricoladb-server/lambroll/**

jobs:
  deploy:
    uses: ./.github/workflows/wf-deploy-lambda.yml
    with:
      working-directory: ./components/agricoladb-server/lambroll
      environment-name: agricoladb-server-production
      environment-url: https://api.db.agricolajp.dev/
      archive-file-repository: AgricolaDevJP/agricoladb-server
      archive-file-name: agricoladb-server-lambda_arm64.zip
    secrets: inherit
