on:
  workflow_call:
    inputs:
      new-version:
        description: new version or revision
        required: true
        type: string
      target-name:
        description: target name
        required: true
        type: string
      target-file:
        description: target manifest file to update
        required: true
        type: string

jobs:
  create-pr:
    name: Create a pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "$NEW_VERSION" > "$TARGET_FILE";
        env:
          NEW_VERSION: "${{ inputs.new-version }}"
          TARGET_FILE: "${{ inputs.target-file }}"
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 792029
          private-key: ${{ secrets.AGRICOLADEVJP_BOT_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Bump ${{ inputs.target-name }} to ${{ inputs.new-version }}
          title: Bump ${{ inputs.target-name }} to ${{ inputs.new-version }}
          body: |
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

            Updated file: ${{ inputs.target-file }}
          token: ${{ steps.app-token.outputs.token }}
          branch: ${{ inputs.target-name }}
